### ISSUE TITLE
Some themes are broken

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocs-gallery#4]
They don't build with latest mkdocs:

- `docskimmer`: https://github.com/hfagerlund/mkdocs-docskimmer/issues/17
- `inspired`: https://github.com/rnason/MKDocs-Inspired/issues/1
- `jinks_en`: https://github.com/anetwork/mkdocs-jinks-theme/issues/4
- `lantana`: https://github.com/WSOFT-Project/lantana/issues/48
- `semantic`: https://github.com/cryocaustik/mkdocs-semantic/issues/9
- `unidata`: issues and discussions are disabled (https://github.com/mjames-upc/mkdocs-unidata)

Also the Gitbook theme shows weird `results matching ""` text: https://gitlab.com/lramage/mkdocs-gitbook-theme/-/issues/18

We should either fix or exclude them.

Check out the logs locally, docskimmer, inspired and jinks_en show:

```
ERROR   -  Config value 'theme': The theme 'docskimmer' does not appear to have a configuration file. Please upgrade to a current version of the theme.

Aborted with 1 configuration errors!
```

Lantana shows:

```
WARNING -  Template skipped: 'version.json' not found in theme directories.
ERROR   -  Error building page 'index.md': 'mkdocs.config.defaults.MkDocsConfig object' has no attribute 'share'
Traceback (most recent call last):
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 349, in build
    _build_page(
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 232, in _build_page
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/lantana/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/lantana/base.html", line 157, in top-level template code
    {% block main_content %}
^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/lantana/main.html", line 101, in block 'main_content'
    <li><button class="btn dropdown-item" onclick="share_to_twitter('{% if page.title %}{{ page.title }} | {% endif %}{{ config.site_name }}','{{ config.share.twitter_params }}');"><i class="bi bi-twitter"></i>&nbsp;Twitter</button></li>
^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/lantana/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'mkdocs.config.defaults.MkDocsConfig object' has no attribute 'share'
```

Semantic shows:

```
Traceback (most recent call last):
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 340, in build
    _build_theme_template(template, env, files, config, nav)
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 110, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 89, in _build_template
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/semantic/404.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/semantic/base.html", line 59, in top-level template code
    {% block navbar %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/semantic/base.html", line 61, in block 'navbar'
    {%- include "includes/navbar.html" %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/semantic/includes/navbar.html", line 3, in top-level template code
    {%- if config.theme.logo.image %}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/semantic/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'mkdocs.theme.Theme object' has no attribute 'logo'
```

Unidata shows:

```
INFO    -  DeprecationWarning: invalid escape sequence '\s'
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/jinja2/lexer.py", line 389, in __next__
    self.current = next(self._iter)
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/jinja2/lexer.py", line 652, in wrap
    .decode("unicode-escape")

ERROR   -  Error building page 'index.md': argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 349, in build
    _build_page(
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 232, in _build_page
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/unidata/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/media/data/dev/mkdocs-gallery/themes/unidata/.venv/lib/python3.11/site-packages/unidata/base.html", line 74, in top-level template code
    {% if "github" in platform %}
^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by asiffer** [comment]
Hi @pawamoy, I notice that [`mkdocs-shadcn`](https://github.com/asiffer/mkdocs-shadcn) has not its screenshot on the [catalog](https://github.com/mkdocs/catalog) so I have landed on this repo. It seems that only `docSkimmer` fails when running `make build`. I did go further since `playwright` failde on my system.

**Comment by pawamoy** [comment]
Hi @asiffer, thanks for the heads up. Unfortunately I'm not investing time into the MkDocs ecosystem anymore, as I'm focusing on [Zensical](https://zensical.org). I'll gladly transfer this repository over to the https://github.com/mkdocs organization if they want to maintain it though.
